apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema" # required

imports:
  - name: cluster
    targetType: landscaper.gardener.cloud/kubernetes-cluster

deployExecutions:
  - name: deploy-execution-payment
    file: /deploy-execution-payment.yaml
    type: GoTemplate
