apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-auth
  namespace: example  # same namespace as the Context
stringData:
  authHeader: "Basic dX3d...cmQ="  # <-------------------------- replace with your auth header
type: Opaque
