apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: subinstallations-example
  annotations:
    landscaper.gardener.cloud/operation: reconcile
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
      componentName: github.com/gardener/landscaper-examples/subinstallations/installation-template
      version: v0.1.0

  blueprint:
    ref:
      resourceName: root-blueprint

  imports:
    targets:
      - name: targetCluster
        target: "target-cluster"

  importDataMappings:
      namespace: test
      chartValues:
        testData: foobar
