apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: create-configmap
  namespace: example
spec:
  blueprint:
    ref:
      resourceName: blueprint

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/manifest-deployer/create-configmap
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry
      version: v0.1.2

  imports:
    targets:
      - name: cluster
        target: '#my-cluster'

    data:
      - name: configmapName
        dataRef: imports-dataobject-name
      - name: contentKey
        dataRef: imports-dataobject-key
      - name: contentValue
        dataRef: imports-dataobject-value
