landscaper:
  landscaper:
    verbosity: 7
    deployers:
      - container
      - helm
      - mock
      - manifest

    deployItemTimeouts:
      # how long deployers may take to react on changes to deploy items
      pickup: 5m
      # how long deployers may take to abort processing a deploy item after the annotation has been set
      abort: 5m
      # default for how long deployers may take to process a deploy item before being aborted, can be overwritten via the deploy item's 'spec.timeout' field
      progressingDefault: 5m
