apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: example-secret-copy
  namespace: example
spec:
  blueprint:
    ref:
      resourceName: blueprint

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/imports/secret-copy
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry
      version: v0.1.1

  imports:
    data:
      - name: exampleData
        secretRef:
          name: secret-copy-imports
          namespace: example
    targets:
      - name: cluster
        target: '#my-cluster'
