apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: example-with-complete-secret
  namespace: example
spec:
  blueprint:
    inline:
      filesystem:
        blueprint.yaml: |
          apiVersion: landscaper.gardener.cloud/v1alpha1
          kind: Blueprint
          jsonSchema: "https://json-schema.org/draft/2019-09/schema"

  imports:
    data:
      - name: accessKeyId
        configMapRef:
          name: example-configmap
          namespace: example
          key: ACCESS_KEY_ID
      - name: secretAccessKey
        configMapRef:
          name: example-configmap
          namespace: example
          key: SECRET_ACCESS_KEY
