apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: container-1
  annotations:
    landscaper.gardener.cloud/operation: reconcile
spec:
  blueprint:
    ref:
      resourceName: blueprint

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/container-deployer/container-1
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry
      version: v0.1.0

  imports:
    targets:
      - name: targetCluster
        target: '#target-cluster'

  importDataMappings:
    configmap:
      name: example-configmap
      namespace: default
      content:
        key: mykey
        value: myvalue

  exports:
    data:
    - name: configMapData
      dataRef: configmapdata

    - name: component
      dataRef: component

    - name: content
      dataRef: content
