apiVersion: v1
kind: ConfigMapList
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ .Release.Name }}-root-1
      namespace: {{ .Release.Namespace }}
    data:
      key1: val1
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ .Release.Name }}-root-2
      namespace: {{ .Release.Namespace }}
    data:
      key2: val2
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ .Release.Name }}-root-3
      namespace: {{ .Release.Namespace }}
    data:
      key3: val3
---
apiVersion: v1
kind: ConfigMapList
items: []
