apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: export-import-2
  namespace: example
spec:
  blueprint:
    ref:
      resourceName: blueprint

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/manifest-deployer/export-import
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry
      version: v0.1.0

  imports:
    targets:
      - name: cluster
        target: '#my-cluster'

    data:
      - name: configmapNameIn
        dataRef: configmap-name-2

  exports:
    data:
      - name: configmapNameOut
        dataRef: configmap-name-3
