apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: create-configmap-from-import
  namespace: example
spec:
  blueprint:
    ref:
      resourceName: blueprint

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/manifest-deployer/create-configmap-from-import
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry
      version: v0.1.0

  imports:
    targets:
      - name: cluster
        target: '#my-cluster'

    data:
      - name: configmapName
        configMapRef:
          name: imports-configmap
          key: configmapName
      - name: contentKey
        configMapRef:
          name: imports-configmap
          key: contentKey
      - name: contentValue
        configMapRef:
          name: imports-configmap
          key: contentValue
