apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema" # required

imports:
  - name: cluster1
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: cluster2
    targetType: landscaper.gardener.cloud/kubernetes-cluster

subinstallations:
  - apiVersion: landscaper.gardener.cloud/v1alpha1
    kind: InstallationTemplate
    name: subinst
    blueprint:
      ref: cd://resources/blueprint-di2
    imports:
      targets:
        - name: cluster1
          target: cluster1
        - name: cluster2
          target: cluster2
