apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: compose-list-exec-root
  namespace: cu-example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  context: landscaper-test

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-test/targetlists/compose-list-exec
      version: 1.0.0

  blueprint:
    ref:
      resourceName: blueprint-root

  imports:
    targets:
      - name: rootclustera
        target: red-cluster
      - name: rootclusterb
        target: green-cluster
      - name: rootclusterc
        target: blue-cluster
