apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: scaling-many-deployitems
  namespace: example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  context: landscaper-examples

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/scaling/many-deployitems
      version: 1.0.0

  blueprint:
    ref:
      resourceName: blueprint

  imports:
    targets:
      - name: cluster
        target: my-cluster

    data:
      - name: values
        dataRef: my-values
      - name: releases
        dataRef: my-releases
