apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Context
metadata:
  name: landscaper-examples-artifactory
  namespace: example

repositoryContext:
  baseUrl: eu.gcr.io/gardener-project/landscaper/examples
  type: ociRegistry

configurations:
  helmChartRepoCredentials:
    auths:
      - url: "https://common.repositories.cloud.sap/artifactory/landscaper-examples"
        authHeader: "Basic dX3d...cmQ="  # <-------------------------- replace with your auth header
