apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  annotations:
    landscaper.gardener.cloud/operation: reconcile
  name: helm-tp
  namespace: example

spec:
  blueprint:
    ref:
      resourceName: blueprint

  context: helm-repo-protected

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/helm-deployer/helm-tp
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry
      version: v0.1.0

  # specify values for the import parameters of the blueprint
  imports:
    targets:
      - name: cluster        # name of an import parameter of the blueprint
        target: my-cluster   # name of the Target custom resource containing the kubeconfig of the target cluster
    data:
      - name: helmvalues     # name of an import parameter of the blueprint
        dataRef: my-imports  # name of the DataObject custom resource containing the value for the import parameter
