apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema" # required

imports:
  - name: cluster1
    targetType: landscaper.gardener.cloud/kubernetes-cluster

deployExecutions:
  - name: default
    type: GoTemplate
    template: |
      deployItems:
        - name: item1
          type: landscaper.gardener.cloud/kubernetes-manifest
          target:
            import: cluster1
          config:
            apiVersion: manifest.deployer.landscaper.gardener.cloud/v1alpha2
            kind: ProviderConfiguration
            updateStrategy: update
            manifests:
              - policy: manage
                manifest:
                  apiVersion: v1
                  kind: ConfigMap
                  metadata:
                    name: test1
                    namespace: example
                  data:
                    foo: bar
