apiVersion: batch/v1
kind: Job
metadata:
  name: pause-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pause-job
          image: "gcr.io/google_containers/pause:3.1"
