apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema"

imports:
  - name: rootclustersingle
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: rootclustera
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: rootclusterb
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: rootclusterc
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

subinstallations:
  - file: /subinst.yaml
