apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema" # required

imports:
  - name: cluster
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: configmapNameIn
    required: true
    type: data
    schema:
      description: name of the configmap which the blueprint creates.
      type: string

subinstallations:
  - file: /subinstallation-1.yaml
  - file: /subinstallation-2.yaml
