apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate
name: subinst1
blueprint:
  ref: cd://componentReferences/my-sub-component/resources/blueprint

imports:
  targets:
    - name: cluster
      target: cluster

  data:
    - name: configmap-name-in
      dataRef: configmap-name-base

exports:
  data:
    - name: configmap-name-out
      dataRef: configmap-name-2
