apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: targetCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: namespace
    required: true
    type: data
    schema:
      type: string

  - name: chartValues
    required: true
    type: data
    schema:
      type: object

exports: []

subinstallationExecutions:
  - name: "charts"
    file: /charts-subinst.yaml
    type: GoTemplate
