{{- $releaseName := .Release.Name }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $text := .Values.text }}
{{- range $index := .Values.numOfCm | int | until }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $index }}
  namespace: {{ $releaseNamespace }}
data:
  testData: |
    {{- $text | toYaml | nindent 4 }}
{{- end }}