apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema"

imports:
- name: targetCluster
  required: true
  targetType: landscaper.gardener.cloud/kubernetes-cluster

- name: configmap
  required: true
  schema:
    type: object
    properties:
      name:
        type: string
      namespace:
        type: string
      content:
        type: object
        properties:
          key:
            type: string
          value:
            type: string

exports:
- name: configMapData
  schema:
    type: object

- name: component
  schema:
    type: object

- name: content
  schema:
    type: array

deployExecutions:
  - name: deploy-execution
    type: GoTemplate
    file: /deploy-execution.yaml

exportExecutions:
  - name: export-execution
    type: GoTemplate
    file: /export-execution.yaml
