apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: helm-3
  namespace: cu-example

spec:
  blueprint:
    ref:
      resourceName: blueprint

  context: helm-repo-protected

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/helm-deployer/helm-3
      version: v0.1.0

  imports:
    targets:
      - name: cluster
        target: 'my-cluster'
