apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: sock-shop
  namespace: sock-shop-inst
spec:
  blueprint:
    ref:
      resourceName: blueprint

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/sock-shop/one-deploy-item
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry
      version: v0.1.0

  imports:
    targets:
      - name: cluster
        target: '#my-cluster'
