apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: instances-root
  namespace: cu-example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  context: landscaper-test

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-test/targetmaps/instances
      version: 1.0.0

  blueprint:
    ref:
      resourceName: blueprint-root

  imports:
    data:
      - name: instances
        dataRef: do-instances
      - name: configs
        dataRef: do-config
    targets:
      - name: clusters
        targetMap:
          blue: blue-cluster
          green: green-cluster
          yellow: yellow-cluster
          orange: orange-cluster
          red: red-cluster
