apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: compose-map-exec-root
  namespace: cu-example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  context: landscaper-test

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-test/targetmaps/compose-map-exec
      version: 1.0.0

  blueprint:
    ref:
      resourceName: blueprint-root

  imports:
    targets:
      - name: redRootCluster
        target: red-cluster
      - name: blueRootCluster
        target: green-cluster
      - name: greenRootCluster
        target: blue-cluster
