apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: create-configmaps-export-import
  namespace: example
spec:
  blueprint:
    ref:
      resourceName: blueprint

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/subinstallations/export-import
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry
      version: v0.1.0

  imports:
    targets:
      - name: cluster
        target: '#my-cluster'
