apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema"

imports:
  - name: subclustersingle
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: subclustera
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: subclusterb
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: subclusterc
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

subinstallations:
  - file: /subinst.yaml
