apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: helm-4
  namespace: cu-example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  context: landscaper-examples

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/helm-deployer/helm-4
      version: v0.1.1

  blueprint:
    ref:
      resourceName: blueprint

  imports:
    targets:
      - name: cluster
        target: 'my-cluster'

  importDataMappings:
    release:
      name: hallo-4
      namespace: example
    testDataIn: test-4

  exports:
    data:
      - name: testDataOut
        dataRef: do-testdata-out
