apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: helm-chart-1
  namespace: example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  blueprint:
    ref:
      resourceName: blueprint

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/helm-deployer/helm-chart-1
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry
      version: v0.1.0

  imports:
    targets:
      - name: cluster
        target: 'my-cluster'

  importDataMappings:
    release:
      name: hallo
      namespace: example
    testDataIn: test

  exports:
    data:
      - name: testDataOut
        dataRef: do-testdata-out
