apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testresources.landscaper.gardener.cloud
spec:
  conversion:
    strategy: None
  group: landscaper.gardener.cloud
  names:
    kind: TestResource
    listKind: TestResourceList
    plural: testresources
    shortNames:
      - tr
    singular: testresource
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Test custom resource definition
          properties:
            spec:
              type: object
            status:
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
