meta:
  schemaVersion: 'v2'
component:
  name: 'github.com/gardener/landscaper-examples/subinstallations/create-configmaps-imports'
  version: 'v0.1.0'

  repositoryContexts:
    - type: 'ociRegistry'
      baseUrl: 'eu.gcr.io/gardener-project/landscaper/examples'

  provider: 'internal'

  componentReferences:
  - name: my-sub-component
    componentName: github.com/gardener/landscaper-examples/manifest-deployer/create-configmap
    version: v0.1.0

  sources: []

  resources: []
