apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: di-per-target-gotemplate
  annotations:
    "landscaper.gardener.cloud/operation": reconcile
spec:
  blueprint:
    inline:
      filesystem:
        blueprint.yaml: |
          apiVersion: landscaper.gardener.cloud/v1alpha1
          kind: Blueprint

          imports:
          - name: mytargets
            type: targetList
            targetType: landscaper.gardener.cloud/kubernetes-cluster
          
          deployExecutions:
          - name: deploy-executions
            type: GoTemplate
            template: |
              deployItems:
              {{ range $idx, $target := .imports.mytargets }}
              - name: my-di-{{ $idx }}-{{ $target.metadata.name }}
                type: landscaper.gardener.cloud/kubernetes-manifest
                target:
                  import: mytargets
                  index: {{ $idx }}
                config:
                  apiVersion: manifest.deployer.landscaper.gardener.cloud/v1alpha2
                  kind: ProviderConfiguration
                  manifests:
                  - policy: manage
                    manifest:
                      apiVersion: v1
                      kind: Secret
                      metadata:
                        name: foo-{{ $idx }}
                        namespace: default
                      data:
                        foo: YmFy
              {{ end }}
  componentDescriptor:
    inline:
      component:
        componentReferences: []
        name: targetlist-installation
        provider: internal
        repositoryContexts:
        - baseUrl: example.com/test
          type: ociRegistry
        resources: []
        sources: []
        version: 1.0.0
      meta:
        schemaVersion: v2
  context: default
  imports:
    targets:
    - name: mytargets
      targets:
      - target-cluster
      - target-cluster
      - target-cluster
