apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: inst-per-target-spiff
  annotations:
    "landscaper.gardener.cloud/operation": reconcile
spec:
  blueprint:
    inline:
      filesystem:
        blueprint.yaml: |
          apiVersion: landscaper.gardener.cloud/v1alpha1
          kind: Blueprint

          imports:
          - name: mytargets
            type: targetList
            targetType: landscaper.gardener.cloud/kubernetes-cluster
          
          subinstallationExecutions:
          - name: subinst-executions
            type: Spiff
            template:
              subinstallations: (( sum[imports.mytargets|[]|s,idx,tar|-> s *iTemplate] ))
              iTemplate:
                <<<: (( &template &temporary ))
                apiVersion: landscaper.gardener.cloud/v1alpha1
                kind: InstallationTemplate
                name: (( "my-subinst-" idx "-" tar.metadata.name ))
                imports:
                  targets:
                  - target: (( "mytargets[" idx "]" ))
                    name: mytarget
                blueprint:
                  filesystem:
                    blueprint.yaml: (( asyaml(rawBlueprint) ))
                    rawBlueprint:
                      <<<: (( &temporary ))
                      apiVersion: landscaper.gardener.cloud/v1alpha1
                      kind: Blueprint
                      imports:
                      - name: mytarget
                        type: target
                        targetType: landscaper.gardener.cloud/kubernetes-cluster
                      deployExecutions:
                      - name: deployitems
                        type: Spiff
                        template:
                          deployitems:
                          - name: mydeployitem
                            type: landscaper.gardener.cloud/kubernetes-manifest
                            target:
                              import: mytarget
                            config:
                              apiVersion: manifest.deployer.landscaper.gardener.cloud/v1alpha2
                              kind: ProviderConfiguration
                              manifests:
                              - policy: manage
                                manifest:
                                  apiVersion: v1
                                  kind: Secret
                                  metadata:
                                    name: (( "foo-" idx ))
                                    namespace: default
                                  data:
                                    foo: YmFy
  componentDescriptor:
    inline:
      component:
        componentReferences: []
        name: targetlist-installation
        provider: internal
        repositoryContexts:
        - baseUrl: example.com/test
          type: ociRegistry
        resources: []
        sources: []
        version: 1.0.0
      meta:
        schemaVersion: v2
  context: default
  imports:
    targets:
    - name: mytargets
      targets:
      - target-cluster
      - target-cluster
      - target-cluster
