apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema"

imports:
  - name: cluster
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: release
    required: true
    type: data
    schema:
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string
  - name: testDataIn
    required: true
    type: data
    schema:
      type: string

exports:
  - name: testDataOut
    type: data
    schema:
      type: string

deployExecutions:
  - name: default-deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate

exportExecutions:
  - name: default-export-execution
    file: /export-execution.yaml
    type: GoTemplate
