apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: multiple-items
  namespace: cu-example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  context: landscaper-test

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-test/targetlists/multiple-items
      version: 1.0.0

  blueprint:
    ref:
      resourceName: blueprint

  imports:
    targets:
      - name: clusters
        targets:
          - red-cluster
          - green-cluster
          - blue-cluster
    data:
      - name: colors
        dataRef: colors
