apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Context
metadata:
  name: protected-helm-repo
  namespace: example

repositoryContext:
  baseUrl: eu.gcr.io/gardener-project/landscaper/examples
  type: ociRegistry

registryPullSecrets: []

configurations:
  helmChartRepoCredentials:
    - url: https://sap-hub-stable.storage.googleapis.com
      authHeader: TO_BE_REPLACED
