apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: protected-helm-repo
  namespace: example

spec:
  blueprint:
    ref:
      resourceName: blueprint

  context: protected-helm-repo

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/helm-deployer/protected-helm-repo
      version: v0.1.0

  imports:
    targets:
      - name: cluster
        target: '#my-cluster'

  importDataMappings:
    helmDeployment: true
