apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema" # required

imports:
  - name: cluster
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: vpa
    required: false
    schema:
      $ref: "blueprint://schemas/vpa.json"

deployExecutions:
  - name: default-deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate
