apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: single-item
  namespace: cu-example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  context: landscaper-test

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-test/targetlists/single-item
      version: 1.0.0

  blueprint:
    ref:
      resourceName: blueprint

  imports:
    targets:
      - name: cluster
        target: orange-cluster
